### ISSUE TITLE
Crash due to "java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte"

### ISSUE THREAD

**Issue by daneKKK** [Hummel009/LOTR-Storage#1]
Причина: Для классов lotr.common.entity.animal.LOTREntityHorse, lotr.common.entity.item.LOTREntityBannerWall и lotr.common.entity.item.LOTREntityTraderRespawn неправильно записываются данные через dataWatcher.addObject(...., (Object) 0) и dataWatcher.updateObject(...., (Object) 0). Фиксится, конечно, кастом (byte) 0 там, где игра ожидает увидеть byte. Залить архив с исправлениями я в ближайшее время не могу, потому что я уже сильно покопался в моде.

**Comment by Hummel009** [comment]
В архиве -src ломанные исходники, да, это я знаю. Хороший исходник в архиве -repo

**Comment by daneKKK** [comment]
Да, имею в виду -repo, пригодный к компиляции из коробки.

**Comment by Hummel009** [comment]
Спасибо, поправил. Видимо, я во время исправления похожих мест через поиск не зацепил папку животных и предметов
